package com.starmap.app.ui

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

class ReleaseNotesTest {
    @Test
    fun autoGeneratedBodyBecomesALinkOnly() {
        val p = ReleaseNotes.parse(
            "**Full Changelog**: https://github.com/Pr0zak/Starmap/compare/v2.2.5...v2.3.0",
        )
        assertEquals("", p.text)
        assertEquals("https://github.com/Pr0zak/Starmap/compare/v2.2.5...v2.3.0", p.changelogUrl)
    }

    @Test
    fun markdownMarkersAreStripped() {
        val p = ReleaseNotes.parse("## What's new\n* **Sky alerts** for `meteor` peaks\n- [Docs](https://x.y)")
        assertEquals("What's new\n• Sky alerts for meteor peaks\n• Docs", p.text)
        assertNull(p.changelogUrl)
    }
}
